version: "3"
services:
  solr1:
    image: wachira90/solr:8.5.2
    container_name: solr1
    ports:
      - "8981:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr
    links:
      - zoo1
      - zoo2

  solr2:
    image: wachira90/solr:8.5.2
    container_name: solr2
    ports:
      - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr
    links:
      - zoo1
      - zoo2

  solr3:
    image: wachira90/solr:8.5.2
    container_name: solr3
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181
    networks:
      - solr
    links:
      - zoo1
      - zoo2
#    depends_on:
#      - zoo1
#      - zoo2

  zoo1:
    image: wachira90/zookeeper:3.6.1
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181
    volumes:
      - ./vconf1/zoo.cfg:/conf/zoo.cfg
    networks:
      - solr

  zoo2:
    image: wachira90/zookeeper:3.6.1
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181
    volumes:
      - ./vconf2/zoo.cfg:/conf/zoo.cfg
    networks:
      - solr

#volumes:
#  vdata:
#  vconf1:./vconf1/zoo.cfg
#  vconf2:./vconf2/zoo.cfg


networks:
  solr:
